In [2]:
import torch
from torch.testing._internal.two_tensor import TwoTensor
torch.manual_seed(123)

class Log(torch.utils._python_dispatch.TorchDispatchMode):
    def __torch_dispatch__(self, func, types, args, kwargs=None):
        if TwoTensor in types:
            return NotImplemented
        res = func(*args, **kwargs)
        if func is torch.ops.aten.mul.Tensor:
            print(f"\n{func}(*{args}, **{kwargs})")
            print(res)
        return res

a = torch.tensor([1+1j], dtype=torch.complex64,  requires_grad=True)
b = torch.randn((1,), dtype=torch.complex64)

with Log():
    a * b.conj()

a = TwoTensor(a, a.clone())
b = TwoTensor(b, b.clone())

with Log():
    a * b.conj()




aten.mul.Tensor(*(tensor([1.+1.j], requires_grad=True), tensor([-0.0788-0.0851j])), **{})
tensor([0.0063-0.1639j])

aten.mul.Tensor(*(tensor([1.+1.j], requires_grad=True), tensor([-0.0788-0.0851j])), **{})
tensor([-0.1639+0.0063j])

aten.mul.Tensor(*(tensor([1.+1.j], grad_fn=<CloneBackward0>), tensor([-0.0788-0.0851j])), **{})
tensor([-0.1639+0.0063j])


In [ ]:
aten.mul.Tensor(*(tensor([1.+1.j], device='cuda:0', requires_grad=True), tensor([0.9469-0.1451j], device='cuda:0')), **{})
tensor([1.0920+0.8018j], device='cuda:0')

aten.mul.Tensor(*(tensor([1.+1.j], device='cuda:0', requires_grad=True), tensor([0.9469-0.1451j], device='cuda:0')), **{})
tensor([0.8018+1.0920j], device='cuda:0')

aten.mul.Tensor(*(tensor([1.+1.j], device='cuda:0', grad_fn=<CloneBackward0>), tensor([0.9469-0.1451j], device='cuda:0')), **{})
tensor([0.8018+1.0920j], device='cuda:0')